const member = {
    dataMember: {

        Audrey: {
            profile: "/odiProfile.jpg",
            nama: "Audrey Glacia Cipta",
            bod: "24 Agustus",
            horoskop: "Virgo",
            tinggi: "180",
            callsign: "Audrey",
            email: "audrey.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "member",
            instagram: "audreyygl_",
            twitter: "Oddyeo",
            message: "Semangat !!. Jangan pernah Putus Asa >.<",
            tiktok: "-",
        },
        Aurell: {
            profile: "/aurellProfile.jpg",
            nama: "Syahla Nazmi NoorAurell",
            bod: "03 Januari",
            horoskop: "Capricorn",
            tinggi: "180",
            callsign: "Aurell",
            email: "audrey.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "member",
            instagram: "__babyaurell",
            twitter: "babyyaurell",
            tiktok: "-",
            message: "Senang Bertemu Kalian Semua >.<",
            videojiko: "/video/example.mp4",
        },
        Nabilla: {
            profile: "/nabiProfile.jpg",
            nama: "Nabila Agnia Putri",
            bod: "18/03/2001",
            horoskop: "Sagitarius",
            tinggi: "180",
            callsign: "Nabilla",
            email: "audrey.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "member",
            instagram: "hola.bilaaa",
            twitter: "urbabylaa",
            message: "Diam bukan berarti aku ga perhatian loh >.<",
            tiktok: "www.google.com",
        },
        Nara: {
            profile: "/naraProfile.jpg",
            nama: "Nazwa Zahra",
            bod: "03 May",
            horoskop: "Taurus",
            tinggi: "180",
            callsign: "Nara",
            email: "nara.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Bali",
            role: "member",
            instagram: "hynnaraa",
            twitter: "hynnaraaa",
            message: "Senyumku mengalihkan seluruh duniamu >.<",
            tiktok: "",
        },
        Viola: {
            profile: "/vioProfile.jpg",
            nama: "Viola Erlanda Cipta",
            bod: "17 May",
            horoskop: "Taurus",
            tinggi: "180",
            callsign: "Viola",
            email: "viola.avenue@gmail.com",
            notelp: "058668558858",
            asal: "Tasikmalaya",
            role: "captain",
            instagram: "shinviooo",
            twitter: "violaercipta",
            message: "Si Pemanah yang akan memanah hatimu >.<",
            tiktok: "www.google.com",
        },

    },


};

export {
    member,
};